## Before Mid

In [ ]:
hw = "Hello World"
print( hw )

Hello World


In [ ]:
print("Hello World")

Hello World


In [ ]:
print(2**(1/2))

1.4142135623730951


In [ ]:
x = int( input() )
print(x)

34
34


In [ ]:
print(  not(3<=2) or (6>2)  )

True


In [ ]:
print(2*5/5)

2.0


In [ ]:
name = input("Please Enter your name: ")
id = input("Please Enter your id: ")
print("Name:",name,", ID:",id)
print( f"Name: {name} , ID: {id}" )

Please Enter your name: Iqra
Please Enter your id: 12345
Name: Iqra , ID: 12345
Name: Iqra , ID: 12345


In [ ]:
n1 = int(input("Please Enter First Number: "))
n2 = int(input("Please Enter Second Number: "))
print( f"{n1} / {n2} = {n1/n2}" )

Please Enter First Number: 3
Please Enter Second Number: 2
3 / 2


In [ ]:
#Take an integer input from the user
#Print the square of integer if it's a positive number
n = int(input("Please Enter a Number: "))
if n>=0:
    print(n**2)

Please Enter a Number: -7


In [ ]:
n1 = int(input("Please Enter First Number: "))
n2 = int(input("Please Enter Second Number: "))

if n1>=n2:
    print("The largest number is",n1)
elif n1==n2:
    print("Both numbers are equal")
else:
    print("The largest number is",n2)
print("The End")

Please Enter First Number: 100
Please Enter Second Number: 100
The largest number is 100
Both numbers are equal
The End


In [ ]:
x = 10 > 6 + 5 or True
if x:
    print('wtf')

wtf


 Take 3 inputs from the user.\
 First two inputs are float numbers.\
 The third input would be a symbol among the 4 math operators (+, -, *, /).\
 Show the corresponding output depending on the symbol.\
Sample Input 1:\
5.0\
6.0\
*\
Sample output 1:\
5.0 * 6.0 = 30.0\
\
Sample Input 2:\
5.0\
2.0\
/\
Sample output 2:\
5.0 / 2.0 = 2.5\

In [ ]:
n1 = float(input())
n2 = float(input())
sym = input()

if sym == '+':
    print( f"{n1} + {n2} = {n1+n2}" )
else:
    print( f"{n1} - {n2} = {n1-n2}" )
if sym == '*':
    print( f"{n1} * {n2} = {n1*n2}" )
else:
    print( f"{n1} / {n2} = {n1/n2}" )

4


In [ ]:
s1 = "abc"
s2 = "b"
print( s1*5 )

abc-abc-abc-abc-abc-


In [ ]:
brand = input("Enter the car brand: ")
wheel = input("Wheel Left or Right?: ")
hp = int( input("HorsePower? : ") )
tax = 0
if brand == 'Ferrari':
    tax += 30
elif brand == 'Ford':
    tax += 25
if wheel == 'Left':
    tax += 10
if hp > 2000:
    tax += 10
print(f"Extra Tax: {tax}%")

Enter the car brand: Ferrari
Wheel Left or Right?: Left
HorsePower? : 2000
Extra Tax: 40%


In [ ]:
x = input()
if '6' in '0123456789':
    print("It's a number")
else:
    print("Not a number")

6
It's a number


In [ ]:
print('21' in '0123456789')

False


In [ ]:
i=1
while i<=5:
    print(i)
    i+=1
print(i)

1
2
3
4
5
6


In [ ]:
name = input("Enter your name: ")
n = int(input("How many times print?"))
i=1
while i<n*10:
    print(name)
    i*=2

Enter your name: Iqra
How many times print?2
Iqra


In [ ]:
n = int( input("Enter a number: ") )
i=1
while i<=n:
    print(i, end=' ')
    i+=1

Enter a number: 5
1 2 3 4 5 

In [ ]:
i=1
while i<=100:
    if i%7==0 or i%3==0:
        print(i, end=' ')
    i+=1

In [ ]:
i=1
while i<=100:
    if i%2==0:
        print("Even",i)
    else:
        print("Odd",i)
    i+=1


In [ ]:
print(7%3)
print(-7%-3)
print(-7%3)
print(7%-3)

1
-1
2
-2


In [ ]:
n= int(input())
if (n%5==0 or n%7==0) and not(n%5==0 and n%7==0):
    print('Yes')
else:
    print('No')

25
Yes


In [ ]:
x = float('inf')
print(x)
x = float('-inf')
print(x)

inf
-inf


In [ ]:
# 1 5 4 10 7 15 10 20 13 25 16 30 ..........
n=12
i=1
j=1
k=5
while i<=n:
    if i%2==0:
        print(k,end=' ')
        k+=5
    else:
        print(j,end=' ')
        j+=3
    i+=1
print()

1 5 4 10 7 15 10 20 13 25 16 30 


In [ ]:
# Take 5 integer inputs from the user to find the maximum value among them
max = int(input())
i=0
while i<4:
    x = int(input())
    if x > max:
        max = x
    i+=1
print('The Maximum number is:',max)

4
9
10
-2
4
The Maximum number is: 10


In [ ]:
# Take 5 integer inputs from the user to find the maximum value among them
min = int(input())
i=0
while i<4:
    x = int(input())
    if x < min:
        min = x
    i+=1
print('The Minimum number is:',min)

43
-43
0
3
-30
The Minimum number is: -43


In [ ]:
cred = int(input())
cg = float(input())
fee = cred*8000
sch = 0
if cg==4.0:
    sch = 100
elif cg>=3.9:
    sch = 75
elif cg>=3.85:
    sch = 25
elif cg>=3.8:
    sch = 10
print(fee)
print(fee-fee*sch/100)

In [ ]:
i=10
while i<50:
    print(i,end=" ")
    i-=10

10 

In [ ]:
for i in range(1,21,1):
    if i%2==0:
        print(i,end=' ')

2 4 6 8 10 12 14 16 18 20 

In [ ]:
x = float("-inf")
print(x)

True


In [ ]:
n = int(input("How many numbers to take input? "))
for i in range(n):
    x = int(input())
    if x%2==0:
        break
print("The end")

How many numbers to take input? 5
34
The end


Take 10 inputs from the user and print their summation.
While summing up the input value if the summation turns into an even number you'll stop taking inputs and print the summation. Otherwise, print the summation after taking 10 inputs.

In [ ]:
sum = 0
for i in range(10):
    x = int(input())
    if x%2==0:
        continue
        print("Even")
    else:
        print("Odd")

Take one input from the user. Find all divisors of the user input.

In [ ]:
n = int(input())
#for i in range(1,n+1):
    if n%i==0:
        print(i, end=' ')

5
1 5 

In [ ]:
s = "Python Fun"
for i in range(len(s)):
    print(i, s[i])

0 P
1 y
2 t
3 h
4 o
5 n
6  
7 F
8 u
9 n


Take a string input from the user and print only the characters in the odd indices of the string.

In [ ]:
s = input()
for i in range(len(s)):
    if i%2==1:
        print(s[i],end='')

Python


In [ ]:
s = input()
for i in range(1,len(s),2):
    print(s[i],end='')

Python
yhn

In [ ]:
#     0123456789
s =  "Python Fun"
#neg 10987654321
print( s[::-1] )

nuF nohtyP


In [ ]:
l = [50,25,90,60,1005,12,30]

for n in l:
    print(f"Divisors of {n}",end=': ')
    for i in range(1,n+1,1):
        if n%i==0:
            print(i,end=',')
    print(chr(8))

Divisors of 50: 1,2,5,10,25,50,
Divisors of 25: 1,5,25,
Divisors of 90: 1,2,3,5,6,9,10,15,18,30,45,90,
Divisors of 60: 1,2,3,4,5,6,10,12,15,20,30,60,
Divisors of 1005: 1,3,5,15,67,201,335,1005,
Divisors of 12: 1,2,3,4,6,12,
Divisors of 30: 1,2,3,5,6,10,15,30,


In [ ]:
print(123,end='\n')
print()
print(13,end='')
print()
print(23,end='')
print(3,end='')
print(1,end='')


123

13
2331

In [ ]:
s = input()
up=0
for i in range(len(s)):
    if ord("0") <= ord(s[i]) <= ord("9"):
        up+=1
print(up)

JDS34sd
3


In [ ]:
print("Pyhton"+chr(8))




In [ ]:
#Write a python program to find whether a user input contains "S" or not.
x = input()
if "S" in x:
    print("Yes")
else:
    print("No")

grdfdS
Yes


In [ ]:
#Write a python program to extract the vowels from a string and print it.
s="dsaeifkInldU"
out=''
for i in range(len(s)):
    if s[i] in "aeiouAEIOU":
        out += s[i]
print(out)

aeiIU


In [ ]:
s="ABCD, efgh"
out1=""
out2=""
found = False
for i in range(len(s)):
    if s[i]==',':
        found=True
    elif not found:
        out1+=s[i]
    elif s[i]!=' ':
        out2+=s[i]
print(out1)
print(out1)

ABCD
efgh


In [ ]:
#Lab 1 - I/O
#Lab 2 - Branching

#Lab 3 - Loop [ while / for ]
#Lab 4 - String [ indexing, slicing, loop, ASCII, in, newString ]

# CODING
# TRACING [ marking the loop, trace table, precedence, %, //, break, continue ]

## After Mid

### Functions

In [ ]:
#functin definition
def addTwo(x,y): #2 #5
    print(x+y) #3 #6
#Fucniton Calling
addTwo(8,15) #1
addTwo(10,54) #4
#The #1, #2, #3 are sequence of code execution

23
64


Using Return statements

In [ ]:
#The #1, #2, ..... #6 are sequence of code execution
#the following function returns the square if the parameter's number is even otherwise returns cube
def calc(x):#2
    if x%2==0: #3
        return x**2 #4
    else:
        return x**3
# since the function is returning something we can store the returned value
# after storing the returned value we can use it to further calculate something else as well
n = calc(6) #1 #5 #In this line 36 is being returned and it's being stored in n variable
print(n) #6
print(n+4) #7

36
40


A function always returns in order to exit from the function. Even if we don't explicitely don't mention returning, by default function will return None.

In [ ]:
#The #1, #2, #3, #4 ..... #21 are sequence of code execution
# "#1" means this line will be executed first, #2 means it'll be executed second.. etc etc.
#functin definition
def even_or_odd(n):   #2 | #8 | #15
    if n%2==0:        #3 | #9 | #16
        print("even") #4 |
    else:             #10| #14| #17
        print("odd")  #11| #15| #18
    #return None      #5 | #12| #19   #This line is invisible!!
#Fucniton Calling
even_or_odd(26)       #1 | #6 |
even_or_odd(29)       #7 | #13|
# In the following line the retunred None is being stored in x
x = even_or_odd(29)   #14| #16 | #20
print(x)#                      | #21

even
odd
odd
None


Calling one function inside another function

In [ ]:
#The #1, #2, ..... #11 are sequence of code execution
#the following function returns the True if the parameter's number is even otherwise returns false
def is_even(n): #4
    if n%2==0:  #5
        return True #6
    else:
        return False
def new_calc(x):#2
    if is_even(x)==True: #3 #7 #In this line is_even() function is returning True
        return x**2 #8
    else:
        return x**3
val = new_calc(6) #1 #9
print(val) #10
print(val+4) #11

36
40


In [ ]:
def make_power(num, power): #6 #15 #24
    result = num ** power #7 #16 #25
    return result #8 #17 #26

def make_cube(num): #4 #13 #22
    result = make_power(num, 3) #5 #9 #14 #18 #23 #27
    return result #10 #19 #28

def sum_up(num1, num2, num3): #2
    s1 = make_cube(num1) #3 #11
    s2 = make_cube(num2) #12 #20
    s3 = make_cube(num3) #21 #29
    return s1 + s2 + s3 #30

print(sum_up(1, 2, 3)) #1 #31

36


Global and Local Scopes

In [ ]:
#s=50 has falls under the global scope of the whole code
#the s inside the function falls under the local scope of the function
s=50 #Global Variable s has value of 50
def sum(a,b):
    #a,b,s are local variables inside the function
    #a,b,s are destroyed once the function ends
    s = a+b
    print(s)
sum(2,5)
print(s)

7
50


### Recursion

In [ ]:
print('Using Loop')
i=1
while i<=10:
    print(i)
    i+=1
print('Using Recursion')
def show1to10(i):
    #Base Case
    if i>10:
        return
    #Recursive Case
    else:
        print(i)
        show1to10(i+1)
show1to10(1)

In [ ]:
def show10to1(i):
    #Base Case
    if i==0:
        return
    #Recursive Case
    else:
        print(i)
        show10to1(i-1)
show10to1(10)

10
9
8
7
6
5
4
3
2
1


In [ ]:
def show_N_to_1(n):
    if n==0:
        return
    else:
        print(n,end=' ')
        show_N_to_1(n-1)
n=int(input())
show_N_to_1(n)

In [ ]:
print("Using Loop")
#1+2+3+4+5+6+7+8+9+10+.....+N
N=int(input())
sum=0
i=1
while i<=N:
    sum+=i
    i+=1
print(sum)

print("Using Recursion")
#1+2+3+4+5+6+7+8+9+10+.....+n
#1+sum(2,n)
#1+2+sum(3,n)
#1+2+3+sum(4,n)
def sum1toN(i,n):
    if i==n:
        return n
    else:
        return i+sum1toN(i+1, n)
n = int(input())
x=sum1toN(1,n)
print(x)

[Factorial Recursion Slide](https://docs.google.com/presentation/d/1AIx9x36AWPxbuMstqqsipertBPBE-SIxgLQd-Sp6lOU/edit#slide=id.g27f752b020e_2_0)

In [ ]:
def fact(n):
    if n==0 or n==1:
        return 1
    else:
        return n*fact(n-1)

print( fact(4) )

### Python Lists

In [ ]:
#    0   1  2  3  4 5  6
l = [23,432,4,234,1,2,312]
print( l )
print( l[4] )
l[4] = 100
print( l )

[23, 432, 4, 234, 1, 2, 312]
1
[23, 432, 4, 234, 100, 2, 312]


In [ ]:
for i in range(len(l)):
    print(l[i],end=' ')
print()
for i in range(len(l)-1,-1,-1):
    print(l[i],end=' ')
print()

23 432 4 234 100 2 312 
312 2 100 234 4 432 23 


In [ ]:
lst=[]
n = int(input("How many numbers you want to enter? "))
for i in range(n):
    x=int(input())
    lst.append( x )
print(lst)

How many numbers you want to enter? 4
213
33
-32
-43
[213, 33, -32, -43]


In [ ]:
#summing up all times from a list
l = [-23,432,4,234,-1,2,-312]
summ=0
for i in range(len(l)):
    summ+=l[i]
print(l)
print("Summation:",summ)

[-23, 432, 4, 234, -1, 2, -312]
Summation: 336


In [ ]:
#finding the max and min from a list
l = [-23,432,4,234,-1,2,-312]
max = min = l[0]
for i in range(1,len(l)):
    if l[i]>max:
        max = l[i]
    if l[i]<min:
        min = l[i]
print(lst)
print("Max:",max)
print("Min:",min)

[213, 33, -32, -43]
Max: 432
Min: -312


In [ ]:
#Try to count the even numbers in a list
#Try to find the prime numbers in a list
#Try to create more examples and solve them on your own

In [ ]:
n = int(input())
c=0
for i in range(1,n+1):
    if n%i==0:
        c+=1
if c==2:
    print(n,"is Prime")
else:
    print(n,"is Not prime")

18
18 is Not prime


In [ ]:
l = [1,2,3,4,5,6,7,8,9,10,11,12,423,123,234,456,123,7,4,2342,123,431,432]
for i in range(len(l)):
    n=l[i]
    c=0
    for j in range(1,n+1):
        if n%j==0:
            c+=1
    if c==2:
        print(n,"is Prime")

2 is Prime
3 is Prime
5 is Prime
7 is Prime
11 is Prime
7 is Prime
431 is Prime


In [ ]:
#write a python code that finds all the prime numbers from a list
#then store them in another list. Then print the new list.
l = [1,2,3,4,5,6,7,8,9,10,11,12,423,123,234,456,123,7,4,2342,123,431,432]
primes = []
for i in range(len(l)):
    n=l[i]
    c=0
    for j in range(1,n+1):
        if n%j==0:
            c+=1
    if c==2:
        primes.append( n )
print(primes)

[2, 3, 5, 7, 11, 7, 431]


In [ ]:
l = ['Hello','World.',"I", "Love", "Python"]
new_l = []
for i in range(len(l)):
    if len(l[i])%2==0:
        new_l.append( l[i] )
print(new_l)

['World.', 'Love', 'Python']


In [ ]:
#the only valid symbols are + and -
exprsns = [ [5,'+',4], [3,'-',2], [9,'-',1], [4,'+',4] ]
#The output must be
#[ 9, 1, 8, 8 ]

output = []
for i in range(len(exprsns)):
    exprsn = exprsns[i]
    if exprsn[1]=='+':
        calc = exprsn[0]+exprsn[2]
        output.append(calc)
    elif exprsn[1]=='-':
        calc = exprsn[0]-exprsn[2]
        output.append(calc)
print(output)

[9, 1, 8, 8]


In [ ]:
#             0      1      2      3
exprsns = [ [5,4], [3,2], [9,1], [4,4] ]
x = exprsns[1]
x.append(1)
print(x)
print(exprsns)

[3, 2, 1]
[[5, 4], [3, 2, 1], [9, 1], [4, 4]]


In [ ]:
#             0      1      2      3
exprsns = [ [5,4], [3,2], [9,1], [4,4] ]
x = exprsns[1]
x = x[:]
x.append(1)
print(x)
print(exprsns)

[3, 2, 1]
[[5, 4], [3, 2], [9, 1], [4, 4]]


In [ ]:
#a house-14
a = [1,2,3]
#x house-15
x = a[:]
a.append(100)
print(a)
print(x)

[1, 2, 3, 100]
[1, 2, 3, 100]


### Functions & List

In [ ]:
def check_prime(n):
    c=0
    for i in range(1,n+1):
        if n%i==0:
            c+=1
    if c==2:
        print(n,"is Prime")
    else:
        print(n,"is Not prime")

In [ ]:
def return_prime_list(lst):
    primes = []
    for i in range(len(lst)):
        n=lst[i]
        c=0
        for j in range(1,n+1):
            if n%j==0:
                c+=1
        if c==2:
            primes.append( n )
    return primes


l = [1,2,3,4,5,6,7,8,9,10,11,12,423,123,234,456,123,7,4,2342,123,431,432]
x = return_prime_list(l)
print(x)

[2, 3, 5, 7, 11, 7, 431]


In [ ]:
l = [1,2,3,4,5,6,7,8,9,10,11,12,423,123,234,456,123,7,4,2342,123,431,432]

for i in range(len(l)):
    check_prime(l[i])

### Numpy Array

np.zeros()

In [ ]:
import numpy as np

arr = np.zeros( 6, dtype=int )
print("Before:",arr)
arr[2] = 100
print("After:",arr)

Before: [0 0 0 0 0 0]
After: [  0   0 100   0   0   0]


np.ones()

In [ ]:
import numpy as np

arr = np.ones( 5, dtype=int )
print("Before:",arr)
arr[2] = 12
print("After:",arr)

Before: [1 1 1 1 1]
After: [ 1  1 12  1  1]


np.array()

In [ ]:
import numpy as np

arr = np.array( [1,2,3,4,5] )
print("Before:",arr)
arr[2] = 12
print("After:",arr)

Before: [1 2 3 4 5]
After: [ 1  2 12  4  5]


In [ ]:
import numpy as np

arr = np.zeros( 5, dtype=float )
print("Before:",arr)
arr[2] = 12.5
print("After:",arr)

Before: [0. 0. 0. 0. 0.]
After: [ 0.   0.  12.5  0.   0. ]


In [ ]:
import numpy as np

arr = np.ones( 5, dtype=int )

print("Before:",arr)
arr[2] = 12.42
print("After:",arr)

float64


In [ ]:
import numpy as np

arr = np.array( [-11,22,3,24,5] )

max = arr[0]
for i in range(1,arr.size):
    if arr[i]>max:
        max = arr[i]
print(max)

min = arr[0]
for i in range(1,arr.size):
    if arr[i]<min:
        min = arr[i]
print(min)

24
-11


### Sorting

In [ ]:
#SWAPPING
#      0  1  2  3 4 5
lst = [11,2,44,43,3,2]
print(lst)
bckup = lst[0]
lst[0] = lst[2]
lst[2] = bckup
print(lst)

In [ ]:
import numpy as np
#Selection Sort


arr = np.array( [22,24,-3,1,-5] )
print("###########################")
#Find the minimum number from an array
#Then swap the minimum number with the "first" element of the array
print("Before:",arr)
min_i = 0
for i in range(1,arr.size):
    if arr[i]<arr[min_i]:
        min_i = i
temp = arr[0]
arr[0] = arr[min_i]
arr[min_i] = temp
print("After:",arr)
print("###########################")
#Find the "second" minimum number from an array
#Then swap the minimum number with the "second" element of the array
print("Before:",arr)
min_i = 1
for i in range(2,arr.size):
    if arr[i]<arr[min_i]:
        min_i = i
temp = arr[1]
arr[1] = arr[min_i]
arr[min_i] = temp
print("After:",arr)
print("###########################")
print("Before:",arr)
min_i = 2
for i in range(3,arr.size):
    if arr[i]<arr[min_i]:
        min_i = i
temp = arr[2]
arr[2] = arr[min_i]
arr[min_i] = temp
print("After:",arr)
print("###########################")
print("Before:",arr)
min_i = 3
for i in range(4,arr.size):
    if arr[i]<arr[min_i]:
        min_i = i
temp = arr[3]
arr[3] = arr[min_i]
arr[min_i] = temp
print("After:",arr)
print("###########################")

###########################
Before: [22 24 -3  1 -5]
After: [-5 24 -3  1 22]
###########################
Before: [-5 24 -3  1 22]
After: [-5 -3 24  1 22]
###########################
Before: [-5 -3 24  1 22]
After: [-5 -3  1 24 22]
###########################
Before: [-5 -3  1 24 22]
After: [-5 -3  1 22 24]
###########################


In [ ]:
import numpy as np
#Selection Sort
arr = np.array( [100,54,213,22,-24,-3,1,-5] )

print("Before:",arr)
for j in range(0,arr.size,1):
    min_i = j
    for i in range(j+1,arr.size,1):
        if arr[i]<arr[min_i]:
            min_i = i
    temp = arr[j]
    arr[j] = arr[min_i]
    arr[min_i] = temp
print("After:",arr)

Before: [100  54 213  22 -24  -3   1  -5]
After: [-24  -5  -3   1  22  54 100 213]


In [ ]:
def sel_sort(np_arr):
    for j in range(0,np_arr.size,1):
        min_i = j
        for i in range(j+1,np_arr.size,1):
            if np_arr[i]<np_arr[min_i]:
                min_i = i
        temp = np_arr[j]
        np_arr[j] = np_arr[min_i]
        np_arr[min_i] = temp

import numpy as np
#Selection Sort
arr = np.array( [3,413,22,-32,12,65,1,-5] )
print("Before Sel Sort:",arr)
sel_sort(arr)
print("After Sel Sort:",arr)

Before Sel Sort: [  3 413  22 -32  12  65   1  -5]
After Sel Sort: [-32  -5   1   3  12  22  65 413]


 ### 2D Numpy Array

In [ ]:
import numpy as np

#    row id            0           1          2
arr2D = np.array( [ [1,2,3,4], [9,8,7,2], [5,3,2,1] ] )
#    col id          0 1 2 3    0 1 2 3    0 1 2 3
#   row x col = (3x4)
print(arr2D)
print(arr2D.shape)

[[1 2 3 4]
 [9 8 7 2]
 [5 3 2 1]]
(3, 4)


In [ ]:
arr = np.zeros( (5,4) , dtype=int )
print(arr)
print("============")
row_index = 2
col_index = 2
arr[row_index][col_index]=100
print(arr)
print("============")
row_index = 0
col_index = 0
arr[row_index][col_index]=99
print(arr)
print("============")
row_index = 4
col_index = 3
arr[row_index][col_index]=99
print(arr)
print("============")

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[  0   0   0   0]
 [  0   0   0   0]
 [  0   0 100   0]
 [  0   0   0   0]
 [  0   0   0   0]]
[[ 99   0   0   0]
 [  0   0   0   0]
 [  0   0 100   0]
 [  0   0   0   0]
 [  0   0   0   0]]
[[ 99   0   0   0]
 [  0   0   0   0]
 [  0   0 100   0]
 [  0   0   0   0]
 [  0   0   0  99]]


In [ ]:
#    row id               0           1             2
arr2D = np.array( [ [1,2,3,4,5], [9,8,7,2,1], [5,3,2,1,5] ] )
#    col id          0 1 2 3 4    0 1 2 3 4    0 1 2 3 4
#   row x col = (3x5)
row_len, col_len = arr2D.shape

for r in range(row_len):
    for c in range(col_len):
        print(arr2D[r][c],end=' ')
    print()

1 2 3 4 5 
9 8 7 2 1 
5 3 2 1 5 


In [ ]:
#    row id               0           1             2
arr2D = np.array( [ [1,2,3,4,5], [9,8,7,2,1], [5,3,2,1,5] ] )
#    col id          0 1 2 3 4    0 1 2 3 4    0 1 2 3 4
#   row x col = (3x5)
row_len, col_len = arr2D.shape

for r in range(row_len):
    for c in range(col_len):
        if r==1 or c==2:
            arr2D[r][c]=0
print(arr2D)

[[1 2 0 4 5]
 [0 0 0 0 0]
 [5 3 0 1 5]]


In [ ]:
import numpy as np
arr2D = np.array( [ [1,2,3,4],
                    [9,8,7,2],
                    [5,3,2,1] ] )
#   row x col = (3x4)

def print2D(arr2D):
    row_len, col_len = arr2D.shape
    for r in range(row_len):
        for c in range(col_len):
            print(arr2D[r][c],end=' ')
        print()
print('================')
for c in range(col_len):
    for r in range(row_len):
        print(arr2D[r][c],end=' ')
    print()

1 9 5 
2 8 3 
3 7 2 
4 2 1 


#### Scalar Matrix Multiplication

In [ ]:
def scaler_Matrix_Mul(arr2D,x):
    for r in range(row_len):
        for c in range(col_len):
            arr2D[r][c] = x*arr2D[r][c]

arr2D = np.array( [ [1,2,3,4],
                    [9,8,7,2],
                    [5,3,2,1] ] )

print("Before:")
print(arr2D)
scaler_Matrix_Mul(arr2D, 2)
print("After:")
print(arr2D)

Before:
[[1 2 3 4]
 [9 8 7 2]
 [5 3 2 1]]
After:
[[ 2  4  6  8]
 [18 16 14  4]
 [10  6  4  2]]


#### Matrix Matrix multiplication

In [ ]:
#Matrix_Mul is a function that takes two Matrices
# and returns the new multiplied matrix
def Matrix_Mul(m1, m2):
    m1_row_len, m1_col_len = m1.shape
    m2_row_len, m2_col_len = m2.shape
    if m1_col_len != m2_row_len:
        print("Dimension Mismatch")
        return None

    m3 = np.zeros( (m1_row_len, m2_col_len), dtype="int" )
    m3_row, m3_col = m3.shape
    for r in range(m3_row):
        for c in range(m3_col):
            sum=0
            for k in range(m1_col_len):
                sum += (m1[r][k] * m2[k][c])
            m3[r][c] = sum
    return m3

mat1 = np.array([[1,2,3],
                 [3,2,1]])
mat2 = np.array([[1,2],
                 [0,1],
                 [1,0]])
mat3 = Matrix_Mul(mat1, mat2)
print2D(mat1)
print("X")
print2D(mat2)
print("=")
print2D(mat3)

1 2 3 
3 2 1 
X
1 2 
0 1 
1 0 
=
4 4 
4 8 


### Dictionary

In [ ]:
#            keys   values
stdnt_1 = { "name":"Rayan",
            "id"  : 123,
            "dept":"CSE"}

print(stdnt_1)
stdnt_1["name"]="Iqra"
print(stdnt_1,"| length",len(stdnt_1))
stdnt_1["cg"] = 2.3
print(stdnt_1,"| length",len(stdnt_1))

{'name': 'Rayan', 'id': 123, 'dept': 'CSE'}
{'name': 'Iqra', 'id': 123, 'dept': 'CSE'} | length 3
{'name': 'Iqra', 'id': 123, 'dept': 'CSE', 'cg': 2.3} | length 4


In [ ]:
d = {
    "a":"A",
    "b":"B",
    "c":"C"
}

# for k in d.keys():
#     print(k,"->",d[k])
# for v in d.values():
#     print(v)
# for kv in d.items():
#     print(kv[0],"->",kv[1])
# for k, v in d.items():
#     print(k,"->",v)

a -> A
b -> B
c -> C
