In [ ]:
import sys
sys.stdout = open('python/output.txt', 'w')
sys.stdin = open('python/input.txt', 'r')
n = int(input("Enter the number of terms in the series: "))
s = 0
i=1
j=1
k=5
while j<=n and k<=n:
    if i%2!=0:
        s=s+j
        j+=3
    else:
        s=s+k
        k+=5
        i+=1

print(f"The sum of the series is: {s}")

The error is occurring because you're trying to access the elements of the 2D array as if it were a 1D array.

In your code, Array.size gives the total number of elements in the 2D array, which is 9. But Array has only 3 elements (which are 1D arrays), not 9, so when i is 3 or more, Array[i] is out of bounds.

To iterate over all elements in the 2D array, you need two nested loops: one for the rows and one for the columns. 


***So better use len(arr) insted of arr,size in for loops.***

In [ ]:
#IT gives error 
import numpy as np
Array= np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array

print(Array[1][1])

for i in range(Array.size):# Array.size gives the total number of elements (here it is 3*3 = 9).in the array including all dimensions or rows/collums
    # it cant iterate through 8 elements but the lenth of Array is 3
    print(Array[i])



In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7.5,"b",9,10])# auto converts to float if one element is float. If you include string all thing will converted into string
print(type(arr[0]))
for i in range(arr.size):
    print(arr[i], end=" ")
print("\n","----------y----------" ,end="")
print("\n")

arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(arr2)):
    print(arr2[i], end=" ")



<class 'numpy.str_'>
1 2 3 4 5 6 7.5 b 9 10 
 ----------y----------

[1 2 3] [4 5 6] [7 8 9] 

In [54]:
import numpy as np
arr3=np.full((3, 3), 7,dtype=int)
print(arr3)
print(np.empty((2, 2))) #garbage values which existed in the memory

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2.12199579e-314 4.67296746e-307]
 [8.59674224e-321 1.42810317e-311]]


In [56]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10])

max=min=arr[0]
for i in range(arr.size):
    if arr[i]>max:
        max=arr[i]
    elif arr[i]<min:
        min=arr[i]
        
print(f"Max: {max} Min: {min}")

Max: 10 Min: 1


In [5]:
""" var = input("please enter the list ")[1:-1]  #"[4,15,6]"

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []
res=""
for i in range(len(var)):
    if var[i]!=",":
        res+=var[i]
    else:
        final.append(res)
        res=""
        #Shift allt a
var = input("please enter the list ")[1:-1]  #"[4,15,6]" """

var = input("please enter the list ")[1:-1]  #"[4,15,6]

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []
res = ""
for i in range(len(var)):
    if var[i] != ",":
        res += var[i]
    else:
        final.append(int(res.strip()))
        res = ""
# Add the last element
if res:
    final.append(int(res.strip()))

print(final)

String without the brackets 1,2,3,4,5,6,7 and this is of type <class 'str'>
[1, 2, 3, 4, 5, 6, 7]


In [ ]:
""" list=[for i in range(input("Enter the number of elements: ")):
    list.append(int(input("Enter the element: ")))]
print(list) """
lst = [int(input("Enter the element: ")) for _ in range(int(input("Enter the number of elements: ")))]
print(lst)

In [4]:
(print("hell yeah")) for _ in range(5) #error

SyntaxError: invalid syntax (1031827973.py, line 1)

In [ ]:
""" [expression for item in iterable] """#list comprehension structure
""" [expression for item in iterable] """#list comprehension structure

""" item-->      is a variable that takes each value in the iterable one by one

epression--> is a Python expression that is calculated for each item .

iterable--> is a iterable object/range or collection of objects like list, tuple, set, dictionary, etc. """