In [ ]:
import sys
sys.stdout = open('python/output.txt', 'w')
sys.stdin = open('python/input.txt', 'r')
n = int(input("Enter the number of terms in the series: "))
s = 0
i=1
j=1
k=5
while j<=n and k<=n:
    if i%2!=0:
        s=s+j
        j+=3
    else:
        s=s+k
        k+=5
        i+=1

print(f"The sum of the series is: {s}")

The error is occurring because you're trying to access the elements of the 2D array as if it were a 1D array.

In your code, Array.size gives the total number of elements in the 2D array, which is 9. But Array has only 3 elements (which are 1D arrays), not 9, so when i is 3 or more, Array[i] is out of bounds.

To iterate over all elements in the 2D array, you need two nested loops: one for the rows and one for the columns. 


***So better use len(arr) insted of arr,size in for loops.***

In [17]:
import numpy as np

Array= np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array

print(Array[1][1])

for i in range(Array.size):# Array.size gives the total number of elements in the array including all dimensions or rows/collums
    
    print(Array[i])



5
[1 2 3]
[4 5 6]
[7 8 9]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [55]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(arr.size):
    print(arr[i], end=" ")
print("\n","----------y----------" ,end="")
print("\n")

arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(arr2)):
    print(arr2[i], end=" ")



1 2 3 4 5 6 7 8 9 10 
 ----------y----------

[1 2 3] [4 5 6] [7 8 9] 

In [54]:
import numpy as np
arr3=np.full((3, 3), 7,dtype=int)
print(arr3)
print(np.empty((2, 2))) #garbage values which existed in the memory

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2.12199579e-314 4.67296746e-307]
 [8.59674224e-321 1.42810317e-311]]
