In [ ]:
import sys
sys.stdout = open('python/output.txt', 'w')
sys.stdin = open('python/input.txt', 'r')
n = int(input("Enter the number of terms in the series: "))
s = 0
i=1
j=1
k=5
while j<=n and k<=n:
    if i%2!=0:
        s=s+j
        j+=3
    else:
        s=s+k
        k+=5
        i+=1

print(f"The sum of the series is: {s}")

The error is occurring because you're trying to access the elements of the 2D array as if it were a 1D array.

In your code, Array.size gives the total number of elements in the 2D array, which is 9. But Array has only 3 elements (which are 1D arrays), not 9, so when i is 3 or more, Array[i] is out of bounds.

To iterate over all elements in the 2D array, you need two nested loops: one for the rows and one for the columns. 


***So better use len(arr) insted of arr,size in for loops.***

In [ ]:
#IT gives error 
import numpy as np
Array= np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array

print(Array[1][1])

for i in range(Array.size):# Array.size gives the total number of elements (here it is 3*3 = 9).in the array including all dimensions or rows/collums
    # it cant iterate through 8 elements but the lenth of Array is 3
    print(Array[i])



In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7.5,"b",9,10])# auto converts to float if one element is float. If you include string all thing will converted into string
print(type(arr[0]))
for i in range(arr.size):
    print(arr[i], end=" ")
print("\n","----------y----------" ,end="")
print("\n")

arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(arr2)):
    print(arr2[i], end=" ")



<class 'numpy.str_'>
1 2 3 4 5 6 7.5 b 9 10 
 ----------y----------

[1 2 3] [4 5 6] [7 8 9] 

In [54]:
import numpy as np
arr3=np.full((3, 3), 7,dtype=int)
print(arr3)
print(np.empty((2, 2))) #garbage values which existed in the memory

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2.12199579e-314 4.67296746e-307]
 [8.59674224e-321 1.42810317e-311]]


In [56]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10])

max=min=arr[0]
for i in range(arr.size):
    if arr[i]>max:
        max=arr[i]
    elif arr[i]<min:
        min=arr[i]
        
print(f"Max: {max} Min: {min}")

Max: 10 Min: 1


In [5]:
""" var = input("please enter the list ")[1:-1]  #"[4,15,6]"

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []
res=""
for i in range(len(var)):
    if var[i]!=",":
        res+=var[i]
    else:
        final.append(res)
        res=""
        #Shift allt a
var = input("please enter the list ")[1:-1]  #"[4,15,6]" """

var = input("please enter the list ")[1:-1]  #"[4,15,6]

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []
res = ""
for i in range(len(var)):
    if var[i] != ",":
        res += var[i]
    else:
        final.append(int(res.strip()))
        res = ""
# Add the last element
if res:#if res contains something
    final.append(int(res.strip()))

print(final)

String without the brackets 1,2,3,4,5,6,7 and this is of type <class 'str'>
[1, 2, 3, 4, 5, 6, 7]


###[expression for item in iterable] """#list comprehension structure
""" [expression for item in iterable] """#list comprehension structure

""" item-->      is a variable that takes each value in the iterable one by one

epression--> is a Python expression that is calculated for each item .

iterable--> is a iterable object/range or collection of objects like list, tuple, set, dictionary, etc. ###

In [ ]:
""" list=[for i in range(input("Enter the number of elements: ")):
    list.append(int(input("Enter the element: ")))]
print(list) """
lst = [int(input("Enter the element: ")) for _ in range(int(input("Enter the number of elements: ")))]
print(lst)

In [3]:
import numpy as np
lst=[1,2,3,4,5,6,7,8,9,10]

array=np.array(lst)
print(array)


[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
array=np.zeros(6 , dtype=int)
print(array.shape , "shape")
print(array.itemsize, "size in bytes")

print(array.dtype)#data type of the array
print(array.ndim)#number of dimensions
print(array.size)#total number of elements
print(array.nbytes)#total bytes consumed by the elements of the array
print(array.strides)#tuple of bytes to step in each dimension when traversing an array
print(array.data)#buffer object pointing to the start of the array's data
print(array.flags)#information about the memory layout of the array
print(array.base)# what is the base of the array
print(array.T)#transpose
print(array.real)#real part of the array
print(array.imag)#imaginary part of the array
print(array.flat)#1d iterator over the array
print(array.ctypes)#an object to simplify the interaction of the array with the ctypes module
print(array.__array_interface__)#python dictionary exposing the array interface???
print(array.__array_struct__)#python dictionary exposing the array interface???
print(array.__array_priority__)#????
print(array.__array_wrap__)#????
print(array.__array_finalize__)#????
print(array.__array_prepare__)#????
print(array.max())#maximum element
print(array.min())#minimum element
print(array.argmax())#index of the maximum element
print(array.argmin())#index of the minimum element
print(array.ptp())#range of the array (maximum - minimum)
print(array.clip())#clip the array
print(array.conj())#complex conjugate
print(array.round())#round the array
print(array.trace())#sum along the diagonal
print(array.sum())#sum of the array
print(array.cumsum())#cumulative sum of the array
print(array.mean())#mean of the array
print(array.var())#variance of the array
print(array.std())#standard deviation of the array
print(array.prod())#product of the array
print(array.cumprod())#cumulative product of the array
print(array.all())#logical and of the array
print(array.any())#logical or of the array
print(array.nonzero())#indices of the non-zero elements of the array
print(array.sort())#sort the array
print(array.argsort())#indices of the sorted elements of the array
print(array.searchsorted())#indices to insert elements so as to maintain order
print(array.argmax())#index of the maximum element
print(array.argmin())#index of the minimum element
print(array.ptp())#range of the array (maximum - minimum)
print(array.clip())#clip the array
print(array.conj())#complex conjugate
print(array.round())#round the array
print(array.trace())#sum along the diagonal
print(array.sum())#sum of the array
print(array.cumsum())#cumulative sum of the array
print(array.mean())#mean of the array
print(array.var())#variance of the array
print(array.std())#standard deviation of the array
print(array.prod())#product of the array
print(array.cumprod())#cumulative product of the array
print(array.all())#logical and of the array
print(array.any())#logical or of the array
print(array.compress())#return selected slices of an array along given axis
print(array.cumprod())#cumulative product of the array
print(array.cumsum())#cumulative sum of the array
print(array.diagonal())#return specified diagonals
print(array.max())#maximum element
print(array.mean())#mean of the array
print(array.min())#minimum element



(6,) shape
4 size in bytes
int32
1
6
24
(4,)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

None
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


###Arange attribute

In [2]:
#arranges the elements in a given range one after the other
import numpy as np
x = np.arange(10)
y=np.arange(2, 3, 0.1)

print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [17]:
x.shape = (2, 5) 
print(x)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
print(np.zeros((2, 3), dtype=int))
print("\n")
print(np.ones((2, 3), dtype=int))
print("\n")
print(np.full((2, 3), 7, dtype=int))
print("\n")
print(np.empty((2, 3), dtype=int))
print("\n")
print(np.eye(3, dtype=int))
print("\n")
print(np.random.random((2, 3)))
print("\n")
print(np.arange(10, 30, 5))
print("\n")
print(np.linspace(0, 2, 9))
print("\n")
print(np.arange(10000).reshape(100, 100))
print("\n")


[[0 0 0]
 [0 0 0]]


[[1 1 1]
 [1 1 1]]


[[7 7 7]
 [7 7 7]]


[[7 7 7]
 [7 7 7]]


[[1 0 0]
 [0 1 0]
 [0 0 1]]


[[0.0353544  0.30960147 0.80430894]
 [0.58727491 0.71547382 0.76676169]]


[10 15 20 25]


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [94]:
import numpy as np
_3D=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]],dtype=float)
print(_3D.shape)
print(_3D)
print(len(_3D))
print(_3D.ndim)

(2, 3, 3)
[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]]
2
3


#Final term question:    Here, each odd and even keys of the dictionary carry a tuple of names and a tuple of numbers respectively. Your task is to write a python
program to generate the following output dictionary which will return the Total ASCII values of according to the string given here in a decending order.
Input : I 2:("Joey", "Tim", "Jen", "Jack"), 3:("Tom","Jessy")
Output : ('Jen', 285), ('Tim', 298), ('Tom', 304), ('Brad', 377), ('Jack', 377), ('Liam', 387), ('Joey', 407), ('Corey', 514), ('Jessy, 526)

In [149]:
d_input ={1:("Brad","Liam","Corey"), 2:("Joey", "Tim", "Jen", "Jack"), 3:("Tom","Jessy")}
nameList=[]
dictionary_output={}


#print(d_input[1][1],"SEP")

for i in d_input:
    for j in d_input[i]:
       nameList.append(j) 
       
print(nameList)
for that_name in nameList:
    ascii_sum=0
    for j in that_name:
        ascii_sum+=ord(j)
    dictionary_output[that_name]=ascii_sum
print(dictionary_output)

['Brad', 'Liam', 'Corey', 'Joey', 'Tim', 'Jen', 'Jack', 'Tom', 'Jessy']
{'Brad': 377, 'Liam': 387, 'Corey': 514, 'Joey': 407, 'Tim': 298, 'Jen': 285, 'Jack': 377, 'Tom': 304, 'Jessy': 526}


In [151]:
d_input ={1:("Brad","Liam","Corey"), 2:("Joey", "Tim", "Jen", "Jack"), 3:("Tom","Jessy")}
nameList=[]
dictionary_output={}

for i in d_input:
    for j in d_input[i]:
       nameList.append(j) 
#list done
for name in nameList:
    ascii_sum=0
    for char in name:
        ascii_sum+=ord(char)
    dictionary_output[name]=ascii_sum

dictionary_output= sorted(dictionary_output.items(), key=lambda x: x[1], reverse=True)
print(dictionary_output)

[('Jessy', 526), ('Corey', 514), ('Joey', 407), ('Liam', 387), ('Brad', 377), ('Jack', 377), ('Tom', 304), ('Tim', 298), ('Jen', 285)]
