In [ ]:
import sys
sys.stdout = open('python/output.txt', 'w')
sys.stdin = open('python/input.txt', 'r')
n = int(input("Enter the number of terms in the series: "))
s = 0
i=1
j=1
k=5
while j<=n and k<=n:
    if i%2!=0:
        s=s+j
        j+=3
    else:
        s=s+k
        k+=5
        i+=1

print(f"The sum of the series is: {s}")

In [ ]:
#IT gives error 
import numpy as np
Array= np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array

print(Array[1][1])

for i in range(Array.size):# Array.size gives the total number of elements (here it is 3*3 = 9).in the array including all dimensions or rows/collums
    # it cant iterate through 8 elements but the lenth of Array is 3
    print(Array[i])



In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7.5,"b",9,10])# auto converts to float if one element is float. If you include string all thing will converted into string
print(type(arr[0]))
for i in range(arr.size):
    print(arr[i], end=" ")
print("\n","----------y----------" ,end="")
print("\n")

arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(arr2)):
    print(arr2[i], end=" ")



<class 'numpy.str_'>
1 2 3 4 5 6 7.5 b 9 10 
 ----------y----------

[1 2 3] [4 5 6] [7 8 9] 

In [54]:
import numpy as np
arr3=np.full((3, 3), 7,dtype=int)
print(arr3)
print(np.empty((2, 2))) #garbage values which existed in the memory

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2.12199579e-314 4.67296746e-307]
 [8.59674224e-321 1.42810317e-311]]


In [56]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10])

max=min=arr[0]
for i in range(arr.size):
    if arr[i]>max:
        max=arr[i]
    elif arr[i]<min:
        min=arr[i]
        
print(f"Max: {max} Min: {min}")

Max: 10 Min: 1


In [5]:
""" var = input("please enter the list ")[1:-1]  #"[4,15,6]"

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []
res=""
for i in range(len(var)):
    if var[i]!=",":
        res+=var[i]
    else:
        final.append(res)
        res=""
        #Shift allt a
var = input("please enter the list ")[1:-1]  #"[4,15,6]" """

var = input("please enter the list ")[1:-1]  #"[4,15,6]

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []
res = ""
for i in range(len(var)):
    if var[i] != ",":
        res += var[i]
    else:
        final.append(int(res.strip()))
        res = ""
# Add the last element
if res:#if res contains something
    final.append(int(res.strip()))

print(final)

String without the brackets 1,2,3,4,5,6,7 and this is of type <class 'str'>
[1, 2, 3, 4, 5, 6, 7]


###[expression for item in iterable] """#list comprehension structure
""" [expression for item in iterable] """#list comprehension structure

""" item-->      is a variable that takes each value in the iterable one by one

epression--> is a Python expression that is calculated for each item .

iterable--> is a iterable object/range or collection of objects like list, tuple, set, dictionary, etc. ###

In [ ]:
""" list=[for i in range(input("Enter the number of elements: ")):
    list.append(int(input("Enter the element: ")))]
print(list) """
lst = [int(input("Enter the element: ")) for _ in range(int(input("Enter the number of elements: ")))]
print(lst)

In [3]:
import numpy as np
lst=[1,2,3,4,5,6,7,8,9,10]

array=np.array(lst)
print(array)


[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
array=np.zeros(6 , dtype=int)
print(array.shape , "shape")
print(array.itemsize, "size in bytes")

print(array.dtype)#data type of the array
print(array.ndim)#number of dimensions
print(array.size)#total number of elements
print(array.nbytes)#total bytes consumed by the elements of the array
print(array.strides)#tuple of bytes to step in each dimension when traversing an array
print(array.data)#buffer object pointing to the start of the array's data
print(array.flags)#information about the memory layout of the array
print(array.base)# what is the base of the array
print(array.T)#transpose
print(array.real)#real part of the array
print(array.imag)#imaginary part of the array
print(array.flat)#1d iterator over the array
print(array.ctypes)#an object to simplify the interaction of the array with the ctypes module
print(array.__array_interface__)#python dictionary exposing the array interface???
print(array.__array_struct__)#python dictionary exposing the array interface???
print(array.__array_priority__)#????
print(array.__array_wrap__)#????
print(array.__array_finalize__)#????
print(array.__array_prepare__)#????
print(array.max())#maximum element
print(array.min())#minimum element
print(array.argmax())#index of the maximum element
print(array.argmin())#index of the minimum element
print(array.ptp())#range of the array (maximum - minimum)
print(array.clip())#clip the array
print(array.conj())#complex conjugate
print(array.round())#round the array
print(array.trace())#sum along the diagonal
print(array.sum())#sum of the array
print(array.cumsum())#cumulative sum of the array
print(array.mean())#mean of the array
print(array.var())#variance of the array
print(array.std())#standard deviation of the array
print(array.prod())#product of the array
print(array.cumprod())#cumulative product of the array
print(array.all())#logical and of the array
print(array.any())#logical or of the array
print(array.nonzero())#indices of the non-zero elements of the array
print(array.sort())#sort the array
print(array.argsort())#indices of the sorted elements of the array
print(array.searchsorted())#indices to insert elements so as to maintain order
print(array.argmax())#index of the maximum element
print(array.argmin())#index of the minimum element
print(array.ptp())#range of the array (maximum - minimum)
print(array.clip())#clip the array
print(array.conj())#complex conjugate
print(array.round())#round the array
print(array.trace())#sum along the diagonal
print(array.sum())#sum of the array
print(array.cumsum())#cumulative sum of the array
print(array.mean())#mean of the array
print(array.var())#variance of the array
print(array.std())#standard deviation of the array
print(array.prod())#product of the array
print(array.cumprod())#cumulative product of the array
print(array.all())#logical and of the array
print(array.any())#logical or of the array
print(array.compress())#return selected slices of an array along given axis
print(array.cumprod())#cumulative product of the array
print(array.cumsum())#cumulative sum of the array
print(array.diagonal())#return specified diagonals
print(array.max())#maximum element
print(array.mean())#mean of the array
print(array.min())#minimum element



(6,) shape
4 size in bytes
int32
1
6
24
(4,)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

None
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


###Arange attribute

In [2]:
#arranges the elements in a given range one after the other
import numpy as np
x = np.arange(10)
y=np.arange(2, 3, 0.1)

print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [17]:
x.shape = (2, 5) 
print(x)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
print(np.zeros((2, 3), dtype=int))
print("\n")
print(np.ones((2, 3), dtype=int))
print("\n")
print(np.full((2, 3), 7, dtype=int))
print("\n")
print(np.empty((2, 3), dtype=int))
print("\n")
print(np.eye(3, dtype=int))
print("\n")
print(np.random.random((2, 3)))
print("\n")
print(np.arange(10, 30, 5))
print("\n")
print(np.linspace(0, 2, 9))
print("\n")
print(np.arange(10000).reshape(100, 100))
print("\n")


[[0 0 0]
 [0 0 0]]


[[1 1 1]
 [1 1 1]]


[[7 7 7]
 [7 7 7]]


[[7 7 7]
 [7 7 7]]


[[1 0 0]
 [0 1 0]
 [0 0 1]]


[[0.0353544  0.30960147 0.80430894]
 [0.58727491 0.71547382 0.76676169]]


[10 15 20 25]


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [94]:
import numpy as np
_3D=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]],dtype=float)
print(_3D.shape)
print(_3D)
print(len(_3D))
print(_3D.ndim)

(2, 3, 3)
[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]]
2
3


#Final term question:    Here, each odd and even keys of the dictionary carry a tuple of names and a tuple of numbers respectively. Your task is to write a python
program to generate the following output dictionary which will return the Total ASCII values of according to the string given here in a decending order.
Input : I 2:("Joey", "Tim", "Jen", "Jack"), 3:("Tom","Jessy")
Output : ('Jen', 285), ('Tim', 298), ('Tom', 304), ('Brad', 377), ('Jack', 377), ('Liam', 387), ('Joey', 407), ('Corey', 514), ('Jessy, 526)

In [149]:
d_input ={1:("Brad","Liam","Corey"), 2:("Joey", "Tim", "Jen", "Jack"), 3:("Tom","Jessy")}
nameList=[]
dictionary_output={}


#print(d_input[1][1],"SEP")

for i in d_input:
    for j in d_input[i]:
       nameList.append(j) 
       
print(nameList)
for that_name in nameList:
    ascii_sum=0
    for j in that_name:
        ascii_sum+=ord(j)
    dictionary_output[that_name]=ascii_sum
print(dictionary_output)

['Brad', 'Liam', 'Corey', 'Joey', 'Tim', 'Jen', 'Jack', 'Tom', 'Jessy']
{'Brad': 377, 'Liam': 387, 'Corey': 514, 'Joey': 407, 'Tim': 298, 'Jen': 285, 'Jack': 377, 'Tom': 304, 'Jessy': 526}


In [151]:
d_input ={1:("Brad","Liam","Corey"), 2:("Joey", "Tim", "Jen", "Jack"), 3:("Tom","Jessy")}
nameList=[]
dictionary_output={}

for i in d_input:
    for j in d_input[i]:
       nameList.append(j) 
#list done
for name in nameList:
    ascii_sum=0
    for char in name:
        ascii_sum+=ord(char)
    dictionary_output[name]=ascii_sum

dictionary_output= sorted(dictionary_output.items(), key=lambda x: x[1], reverse=True)#sorts the dictionary in descending order of the values
print(dictionary_output)

[('Jessy', 526), ('Corey', 514), ('Joey', 407), ('Liam', 387), ('Brad', 377), ('Jack', 377), ('Tom', 304), ('Tim', 298), ('Jen', 285)]


In [153]:
#sorting Algorithm
#Ascending order
lst=[2,3,1,5,4,6,7,8,9,10]
for i in range(len(lst)):
    for j in range(i+1,len(lst)):
        if lst[i]>lst[j]:
            lst[i],lst[j]=lst[j],lst[i]
print(lst)




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#Selection sort
def selection_sort(lst):
    for i in range(len(lst)):
        min_idx = i
        for j in range(i+1, len(lst)):
            if lst[j] < lst[min_idx]:
                min_idx = j
        lst[i], lst[min_idx] = lst[min_idx], lst[i]
    return lst

lst = [2,3,1,5,4,6,7,8,9,10]
print(selection_sort(lst))

In [ ]:
#Insertion sort
def insertion_sort(lst):
    for i in range(1, len(lst)):
        key = lst[i]
        j = i-1
        while j >= 0 and key < lst[j] :
                lst[j + 1] = lst[j]
                j -= 1
        lst[j + 1] = key
    return lst

lst = [2,3,1,5,4,6,7,8,9,10]
print(insertion_sort(lst))

In [ ]:
#built in sort method
lst = [2,3,1,5,4,6,7,8,9,10]
lst.sort()
print(lst)

In [ ]:
#sorted function
lst = [2,3,1,5,4,6,7,8,9,10]
sorted_lst = sorted(lst)
print(sorted_lst)

In [35]:
import numpy as np
#arr =          r c
arr = np.ones((2,5),dtype=int)
print("Before:",arr*2*33)
""" arr[2] = 12.5
print("After:",arr) """

Before: [[66 66 66 66 66]
 [66 66 66 66 66]]


' arr[2] = 12.5\nprint("After:",arr) '

In [ ]:
f.readline()
f.read()
f.readlines()

In [1]:
lst1=[1,2,3,4,5,6,7,8,9,10]
lst2=[11,12,13,14,15,16,17,18,19,20]
print(lst1+lst2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [2]:
import itertools

lst1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
permutations = list(itertools.permutations(lst1))

# Print the first 10 permutations
for p in permutations[:10]:
    print(p)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
(1, 2, 3, 4, 5, 6, 7, 8, 10, 9)
(1, 2, 3, 4, 5, 6, 7, 9, 8, 10)
(1, 2, 3, 4, 5, 6, 7, 9, 10, 8)
(1, 2, 3, 4, 5, 6, 7, 10, 8, 9)
(1, 2, 3, 4, 5, 6, 7, 10, 9, 8)
(1, 2, 3, 4, 5, 6, 8, 7, 9, 10)
(1, 2, 3, 4, 5, 6, 8, 7, 10, 9)
(1, 2, 3, 4, 5, 6, 8, 9, 7, 10)
(1, 2, 3, 4, 5, 6, 8, 9, 10, 7)


In [3]:
#task 16 
word=input("Word: ")
letter=input("Letter: ")
if letter not in word and len(word)>3:
  print(word[1:len(word)-1])
elif letter in word:
  temp=""
  for i in word:
    if i==letter:
      continue# Avoid adding the letter to the temp string if it is the letter we want to remove // skip the letter
    temp+=i
  print(temp)
else:
  print(word)

kol


In [6]:
#task 10  ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
x=input("Enter:")
count=0
out=""
for i in x:
    if i==",":
        break#End this loop if you find comma
    count+=1#if if is false then counter ++
first=x[:count]
last=x[count+2:]
#print(first)
#print(last)
if len(first)>len(last):
    longer=first
    shorter=last
else:
    longer=last
    shorter= first
for char in range(0,len(shorter)):
    out=out+first[char]+last [char]
for char in range(len(shorter),len(longer)): 
    out=out+longer[char]
print(out)

flaoswt,car,shar


In [8]:
list=[[1,2,3],[4,5,6],[7,8,9]]
y=list[0]
x=list[0].append(10)
list[2].append(10)
print(y)
print(x)
print(list)

[1, 2, 3, 10]
None
[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9, 10]]


In [11]:
list=[[1,2,3],[4,5,6],[7,8,9]]

new=list[:]

print(new,"before")

new=new[0:2] #exclusive of 3rd index

print(new,"after")


[[1, 2, 3], [4, 5, 6], [7, 8, 9]] before
[[1, 2, 3], [4, 5, 6]] after


In [2]:
# Read the input file
with open('arr_info.txt', 'r') as file:
    lines = file.readlines()

# Split the lines into lists of numbers
list1 = [int(num) for num in lines[0].split('-')]
list2 = [int(num) for num in lines[1].split('-')]

# Sum up corresponding elements in the two lists
result_list = []
for i in range(len(list1)):
    result_list.append(str(list1[i] + list2[i]))

# Write the results to the output file without using join
with open('arr_out.txt', 'w') as output_file:
    # Manually concatenate the results with '-'
    for i in range(len(result_list)):
        output_file.write(result_list[i])
        if i < len(result_list) - 1:
            output_file.write('-')

print("Summed up numbers written to arr_out.txt.")


Summed up numbers written to arr_out.txt.


In [5]:
inp=input()
symb=input()

res=""
temp=""


for i in range(len(inp)-1,-1,-1):
    if inp[i]==symb:
        res+=" "
        res+=temp
        temp=""
    else:
        temp+=inp[i]
print(res)


  kooc nac


In [9]:
x=input()
res=""
for i in range(len(x)):
    for j in range(i+1,len(x)):
        if x[i]==x[j]:
            res+="#"
            res+="#"
        else:
            res+=x[i]
print(x)

programming


In [11]:
# Write a python program which takes a string as input and prints a new string by replacing all
# occurrences of repetitive characters with You are not allowed to use the built-in count(),
# replace() function.

x = input()
res = ""
for i in range(len(x)):
    if x[i] in x[:i] or x[i] in x[i+1:]:
        res += "#"
    else:
        res += x[i]
print(res)

p#o##a##in#


In [1]:
myList = [10, 1, 4, 3, 8, 2, 4, 3, 5, 8, "done"]
print(myList[-1:])

['done']


In [2]:
#task 2
x=input("Enter your input: ")
given=int(input("Enter index: "))



i=x[given: :-1]+x[given+1:]




print(i,end="")


dnamarin