In [10]:
#Please install the following packages before running the code
#if you do not then the code will not run
#
import numpy as np


In [12]:
#Task1
import numpy as np

N=int(input())
iarray=np.zeros(N,dtype=int)
for i in range(N):
    iarray[i]=int(input())
    
larray=np.zeros(N+1,dtype=int)

larray[:-1]=iarray#original array ----->>>> the new 

larray[-1]=int(input())# addinnn last element of the new

print("Original Array: ",iarray)
print("Resized Array: ",larray)


Original Array:  [5 8 2]
Resized Array:  [5 8 2 9]


In [ ]:
#Task2
import numpy as np

N=int(input())
arr1d=np.zeros(N,dtype=int)
for i in range(N):
    arr1d[i]=int(input())
print("Orginal array:", arr1d)

for i in range(arr1d.size):
    if arr1d[i] > 0:
        arr1d[i] = 1
    else:
        arr1d[i] = 0

print("Modfied array:", arr1d)

Orginal array: [ 3  4 -2  1]
Modfied array: [1 1 0 1]


In [ ]:
#Task3
import numpy as np

def reverseArray(arr1):
    for start in range(arr1.size // 2): 
        end = arr1.size - 1 - start

        # Swap elements using a temporary variable
        temp = arr1[start]
        arr1[start] = arr1[end]
        arr1[end] = temp

    return arr1


#verification part***********_________***********
arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)
print(arr1)

[ 7  5 20 12 10]


In [ ]:
#Task4
import numpy as np

def printPairs(arr1, target_digit):
    pair_digit = False

    for o in range(arr1.size):
        
        for n in range((o +1), arr1.size):
            
            if arr1[o] + arr1[n] == target_digit:
                
                pair_digit = True
                
                print(f"{arr1[o]}, {arr1[n]}")

    if not pair_digit:
        print("No pair found")
#verification part***********___________***********
arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)

7, 8
10, 5


In [ ]:
#Task5
import numpy as np

vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])
vekktotal = 0

for i in range(vec1.size):
    
    vekktotal += vec1[i] * vec2[i]

if vekktotal % 2 == 0:
    
    for i in range(0, vec1.size, 2):
        
        temp = vec1[i]
        
        vec1[i] = vec2[i]
        
        vec2[i] = temp

else:
    for i in range(1, vec1.size, 2):
        
        temp = vec1[i]
        
        vec1[i] = vec2[i]
        
        vec2[i] = temp
        
#output part***********___________***********



print(f"Dot product: {vekktotal}")

print("After Swapping:")

print(vec1)

print(vec2)


Dot product: 95
After Swapping:
[1 5 3 9]
[4 2 6 7]


In [ ]:
#Task6
import numpy as np

N = int(input())
arr1 = np.zeros(N, dtype = "int")

for i in range(arr1.size):
    arr1[i] = int(input())

print(f"Orginal Array: {arr1}")

for i in range(0, arr1.size-1):
    min_elem = i
    for j in range(i+1, arr1.size):
        if arr1[j] < arr1[min_elem]:
            temp = arr1[j]
            arr1[j] = arr1[min_elem]
            arr1[min_elem] = temp

print(f"Sorted Array: {arr1}")

Orginal Array: [3 6 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [ ]:
#Task7
import numpy as np

def flatten(arr2):
    
    flatten_array = []
    
    for i in range(arr1.shape[0]):
        
        for j in range(arr1.shape[1]):
            
            flatten_array.append(arr1[i][j])

    return np.array(flatten_array)


#verification part   ***********_______***********
arr1 = np.array( [ [1, 2, 3],
                   [3, 4, 5] ] )
arr2 = flatten(arr1)
print(arr2)

[1 2 3 3 4 5]


In [ ]:
#Task8
import numpy as np

A = np.array([ [1, 0, 0],
               [0, 1, 0],
               [0, 0, 1] ])

if A.shape[0] != A.shape[1]:
    
    print("Not an identity matrix")
    
else:
    flaggg = True
    

    for i in range(A.shape[0]):
        
        for j in range(A.shape[1]):
            
            if (i == j and A[i][j] != 1) or (i != j and A[i][j] != 0):
                
                flaggg = False
                
                break

    if flaggg:
        
        print("Identity matrix")
    else:
        
        print("Not an identity matrix")

Identity matrix


In [ ]:
#Task9
import numpy as np

A = np.array([ [1,  5,  12,  1],
                [2,  -4,  6,  7],
                [3,  8,  5,  9],
                [3,  5,  23,  -6] ])

sm_pr_diag = 0

s_2ndry_diag = 0

for i in range(A.shape[0]):
    
    for j in range(A.shape[1]):
        
        if j == i:
            
            sm_pr_diag += A[i][j]
            
        if j ==  A.shape[0] - i -1:
            
            s_2ndry_diag += A[i][j]

absalutttteee = abs( sm_pr_diag - s_2ndry_diag)

print(absalutttteee)

22


In [ ]:
#Task10.1
import numpy as np

A = np.array([[1,2,3,4],
              [1,4,9,16]])

A_finn = np.zeros((A.shape[1], A.shape[0]), dtype="int")

for i in range(A.shape[0]):
    
    for j in range(A.shape[1]):
        
        A_finn[j][i] = A[i][j]

print(A_finn)


[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [ ]:
#Task10.2
import numpy as np

import numpy as np




A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A_trns = np.zeros((A.shape[1], A.shape[0]), dtype="int")

for i in range(A.shape[0]):
    
    for j in range(A.shape[1]):
        
        A_trns[j][i] = A[i][j]

Gram_matrix = np.zeros((A_trns.shape[0], A.shape[1]), dtype="int")

for i in range(A_trns.shape[0]):
    
    for j in range(A.shape[1]):
        
        for k in range(A_trns.shape[1]):
            
            Gram_matrix[i][j] += A_trns[i][k] * A[k][j]

print(Gram_matrix)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [ ]:
#Task11
import numpy as np

A = np.array([[6, 3],
              [1, 5]])

row = A.shape[0]
column = A.shape[1]
absolute_val = abs(row - column)
mod = absolute_val % row

if mod == 0:
    row_to_average = 0
elif mod == 1:
    row_to_average = 1
else:
    row_to_average = row - 1

row_sum = 0
for val in A[row_to_average]:
    row_sum += val

row_size = len(A[row_to_average])
row_avg = row_sum / row_size

A_1 = np.zeros((A.shape[0], A.shape[1]), dtype="float")
for i in range(row):
    for j in range(column):
        A_1[i][j] = row_avg * A[i][j]

print(A_1)

[[27.  13.5]
 [ 4.5 22.5]]
