In [ ]:
import numpy as np




```
import numpy
import numpy as np
import numpy as abc (not a convention)
```





> list can work store multiple data type. But array can store one data type only

>list can have variable length. But array must be declared with a fixed length



In [ ]:
list1 = [4,5]
new_array = np.array(list1)   #new_array = np.array([4,5])


print(new_array, type(new_array))

[4 5] <class 'numpy.ndarray'>


### Zeros




> Different way to put the shape


*   np.zeros(shape = 5)
*   np.zeros(shape = [5])
*   np.zeros(shape = (5))
*   np.zeros(5)
*   np.zeros([5])
*   np.zeros((5))




In [ ]:
zero_array = np.zeros(shape = 5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [ ]:
zero_array2 = np.zeros(shape = 5, dtype= int)
print(zero_array2)

[0 0 0 0 0]


In [ ]:
zero_array3 = np.zeros(shape = 5, dtype= float)
print(zero_array3)

[0. 0. 0. 0. 0.]


In [ ]:
zero_array4 = np.zeros(shape = 5, dtype= str)
print(zero_array4)

['' '' '' '' '']


###Ones

In [ ]:
one_array= np.ones(shape = 5)
print(one_array)

[1. 1. 1. 1. 1.]


In [ ]:
one_array2= np.ones(shape = 5, dtype=str)
print(one_array2)

['1' '1' '1' '1' '1']


## Difference 1 (Data Type storage)


> list: can store different datatypes

> array: can only store ONE data type



In [ ]:
list1 = [4,"A", 3.5,True]
print(list1)

[4, 'A', 3.5, True]


In [ ]:
array1 = np.array([4,"A", 3.5,True])
print(array1)

['4' 'A' '3.5' 'True']


In [ ]:
array2 =  np.array([4, 3.5, True])
print(array2)

[4.  3.5 1. ]


In [ ]:
array3 = np.array([5,8])
print(array3)

[5 8]


In [ ]:
array4 = np.array([5.5,8.2])
print(array4)

[5.5 8.2]


In [ ]:
for elem in array4:
  print(elem)

5.5
8.2


In [ ]:
for i in range(len(array4)):
   print(array4[i])

5.5
8.2


## Difference 2: Adding new element

In [ ]:
list1 = [2,4,5]
list1.append(7)
print(list1)

[2, 4, 5, 7]


In [ ]:
array1 = np.array([2,4,5])
array1.append(7)
print(array1)

AttributeError: ignored

In [ ]:
array2 = np.zeros(shape = (4))

for i in range(len(array1)): #[2 4 5 0]

   array2[i] = array1[i]


array2[3] = 7    #[2  4  5   7]

print(array2)

[2. 4. 5. 7.]


## Adding list vs array

In [ ]:
l1 = [2,3]
l2 = [5,6]

l1 + l2

[2, 3, 5, 6]

In [ ]:
a1 = np.array([2,3])
a2 = np.array([5,6])

print(a1+a2)

[7 9]


In [ ]:
final = np.zeros(shape = len(a1))


for i in range(len(a1)):

   final[i] = a1[i] + a2[i]

print(final)

[7. 9.]


## Element Addition

In [ ]:
sum = 0

for i in range(len(a1)):

   sum += a1[i]

print(sum)

5


# 2D Array

In [ ]:
array_two =  [[2,4,5],
              [1,6,8]]

print(array_two[0])
print(array_two[0][2])

[2, 4, 5]
5


In [ ]:
print(array_two[1])
print(array_two[1][1])

[1, 6, 8]
6


In [ ]:
array_2d = np.zeros(shape = [2,3]) #[row, col]

print(array_2d)



[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array_2d.shape

(2, 3)

In [ ]:
row = array_2d.shape[0]
col = array_2d.shape[1]

print(row,col)

2 3


In [ ]:
array_2d.size

6

In [ ]:
for r in range(0,row):
    for c in range(0, col):
       var = int(input())
       array_2d[r][c] = var

11
22
3
44
55
66


In [ ]:
array_2d = np.array([[11., 22.,  33.],
                     [44., 55., 66.]])



**Row wise traversal**

In [ ]:
for r in range(0,row):
    for c in range(0, col):

       print(array_2d[r][c])  #[0][0] -> [0][1] -> [0][2] -> [1][0] -> [0][1] -> [1][2]

11.0
22.0
33.0
44.0
55.0
66.0


**Column wise traversal**

[[11., 22.,  33.],

[44., 55., 66.]]

In [ ]:


for c in range(0, col):
      for r in range(0,row):
        print(array_2d[r][c])  #[0][0] -> [1][0] -> [0][1] -> [1][1] -> [0][2] -> [1][2]


11.0
44.0
22.0
55.0
33.0
66.0


In [ ]:
array_2d

array([[11., 22., 33.],
       [44., 55., 66.]])

In [ ]:
counter = 0
for inner in array_2d: #inner = [44., 55., 66.]
   for elem in inner:  #elem = 11 , 22 ,33
      counter += 1

print(counter)

6


In [ ]:
row_no = 0
col_no = 0

for inner in array_2d: #inner = [44., 55., 66.]

   for elem in inner:  #elem = 11 , 22 ,33
     col_no += 1

   row_no += 1



col_no = col_no // row_no
print(row_no, col_no)

2 3
