In [5]:
import numpy as np




> list can work store multiple data type. But array can store one data type only

> list can have variable length. But array must be declared with a fixed length



In [7]:
list1 = [4,5]
new_array = np.array(list1)   #new_array = np.array([4,5])


print(new_array, type(new_array))

[4 5] <class 'numpy.ndarray'>


### Zeros

In [32]:
zero_array = np.zeros(shape = 5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [33]:
zero_array2 = np.zeros(shape = 5, dtype= int)
print(zero_array2)

[0 0 0 0 0]


In [34]:
zero_array3 = np.zeros(shape = 5, dtype= float)
print(zero_array3)

[0. 0. 0. 0. 0.]


In [35]:
zero_array4 = np.zeros(shape = 5, dtype= str)
print(zero_array4)

['' '' '' '' '']


###Ones

In [36]:
one_array= np.ones(shape = 5)
print(one_array)

[1. 1. 1. 1. 1.]


In [37]:
one_array2= np.ones(shape = 5, dtype=str)
print(one_array2)

['1' '1' '1' '1' '1']


## Difference 1 (Data Type storage)


> list: can store different datatypes

> array: can only store ONE data type



In [5]:
list1 = [4,"A", 3.5]
print(list1)

[4, 'A', 3.5]


In [6]:
array1 = np.array([4,"A", 3.5])
print(array1)

['4' 'A' '3.5']


In [9]:
array2 =  np.array([4, 3.5])
print(array2)

[4.  3.5]


In [10]:
array3 = np.array([5,8])
print(array3)

[5 8]


In [11]:
array4 = np.array([5.5,8.2])
print(array4)

[5.5 8.2]


## Difference 2: Adding new element

In [12]:
list1 = [2,4,5]
list1.append(7)
print(list1)

[2, 4, 5, 7]


In [13]:
array1 = np.array([2,4,5])
array1.append(7)
print(array1)

AttributeError: ignored

In [22]:
array2 = np.zeros(shape = (4))

for i in range(len(array1)): #[2 4 5 0]

   array2[i] = array1[i]


array2[3] = 7    #[2  4  5   7]

print(array2)

[2. 4. 5. 7.]


## Adding list vs array

In [23]:
l1 = [2,3]
l2 = [5,6]

l1 + l2

[2, 3, 5, 6]

In [26]:
a1 = np.array([2,3])
a2 = np.array([5,6])

print(a1+a2)

[7 9]


In [28]:
final = np.zeros(shape = len(a1))


for i in range(len(a1)):

   final[i] = a1[i] + a2[i]

print(final)

[7. 9.]


## Element Addition

In [39]:
sum = 0

for i in range(len(a1)):

   sum += a1[i]

print(sum)

5


In [9]:
array_two =  [[2,4,5],
             [1,6,8]]

print(array_two[0])
print(array_two[0][2])

[2, 4, 5]
5


In [50]:
print(array_two[1])
print(array_two[1][1])

[1, 6, 8]
6


In [11]:
array_2d = np.zeros(shape = [2,3])

print(array_2d)



[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
row = array_2d.shape[0]
col = array_2d.shape[1]

print(row,col)

2 3


In [13]:
for r in range(0,row):
    for c in range(0, col):
       var = int(input())
       array_2d[r][c] = var

11
22
3
44
55
66


In [15]:
array_2d

array([[11., 22.,  3.],
       [44., 55., 66.]])

In [14]:
for r in range(0,row):
    for c in range(0, col):

       print(array_2d[r][c])

11.0
22.0
3.0
44.0
55.0
66.0
