In [ ]:
import numpy as np

In [ ]:
n = int(input())

array1 = np.zeros(shape = n, dtype = int)  #[0. 0. 0.]

for i in range(n):
     array1[i] = int(input())  #[7. 8.  9.]

print(array1)

3
7
8
9
[7 8 9]


In [ ]:
var = int(input())

array2 = np.zeros(n+1,dtype = int) # [0 0 0 0]

for i in range(n):
     array2[i] = array1[i]  # [7 8 9 0]

print(array2)

array2[- 1] = var # [7 8 9 4]

print(array2)

4
[7 8 9 0]
[7 8 9 4]


In [ ]:
print(len(array1))
print(len(array2))

3
4


### T3

In [ ]:
def reverseArray(arr):

     #rev =  - 1
  for i in range(n//2):

        #swapping of element at i and rev
        rev -= 1

In [ ]:
arr1 = np.array([11,12,13])

flag = False

for i in range(0,len(arr1)-1):
    for j in range(i+1, len(arr1)):
         arr1[i] +arr1[j]
         #if summation == target ?
             # flag = True
             #print the summation


#if flag false, then print pair not found

### T5

In [ ]:
a = 5  # 10
b = 10 # 10

tem = a #tem = 5
a=b
b=tem
print(a,b)


10 5


In [ ]:
a = 5
b = 10

a,b = b,a
print(a,b)

10 5


In [ ]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])

sum = 0


for i in range(len(vec1)):

   sum +=  vec1[i] * vec2[i]


print(sum)

#if even:
#  swap element in even index
if sum % 2 ==0:

      for i in range(len(vec1)):

            if i %2 == 0:
                vec1[i], vec2[i] = vec2[i],vec1[i]


#else
#swap element in odd index

32


In [ ]:
a=1
b = 5
a, b = b,a

print(a,b)

5 1


T7

In [ ]:
array_2d = np.array([ [1, 2, 3],  [3, 4, 5] ])

new_array = np.zeros(shape = array_2d.size)  #[1 2 0 0 0 0]

idx = 0 #idx = 1
for r in range(0,2):
    for c in range(0, 3):

       new_array[idx] = array_2d[r][c]
       idx +=1


print(new_array)

[1. 2. 3. 3. 4. 5.]


In [ ]:
array_2d = np.array([[1,0,0], [0,1,0] ,[0,0,1]])

print(array_2d)

flag = True
for r in range(0,3):
    for c in range(0, 3):

        if r==c: #diagonal
            if array_2d[r][c] != 1:
               flag = False


        else:  #not a diagonal
            if array_2d[r][c] != 0:
               flag = False

print(flag)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
True


In [ ]:
print(abs(1-2))
print(abs(2-1))

1
1


In [ ]:
array_2d = np.array([[1,0,0], [0,1,0] ,[0,0,1]])

print(array_2d)

pri_dia = 0
#variable for secondary diagonal


for r in range(0,3):
    for c in range(0, 3):

        if r==c: #primary diagonal
           pri_dia += array_2d[r][c]

        elif r+c == array_2d.shape[0]-1:#secondary diagonal

             #secondary diagonal addition


#absolute value

In [ ]:
abs(2-6)

4

In [ ]:
A = np.array([[1,2,3,4],
                        [1,4,9,16]])

row = A.shape[0]
col = A.shape[1]

In [ ]:
print(row,col)

2 4


In [ ]:
transpose_2d = np.zeros(shape = (col,row))

transpose_2d

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
for c in range(0, col):
      for r in range(0,row):
        transpose_2d[c][r] = A[r][c]

In [ ]:
transpose_2d

array([[ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

In [ ]:
round(23.412341,2)

23.41

In [ ]:
abs(1)

1